### ISSUE TITLE
Dashboard profile bar is really nice! Some issues, though...

### ISSUE THREAD

**Issue by DominicSimpson** [fac26/week-10-12-tfb-mark-gnnk#68]
- Is that scary avatar image, great as it is, really ideal for 10-year-olds?
- Unfortunately it doesn't do anything atm 😘

**Comment by konstantinakatmada** [comment]
haha well noted, Dominic! The image is a placeholder, it will go.

**Comment by konstantinakatmada** [comment]
After further consultation with our Product Owner, we decided to go with these avatars- children love them!
