### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by DominicSimpson** [fac26/week-10-12-tfb-mark-gnnk#73]
Not sure what's going on here...

![mark-gnnk-errormessage](https://user-images.githubusercontent.com/52511353/228596237-7c28898f-32bd-4b7e-bb23-8fac398088ec.png)

**Comment by tonylomax** [comment]
👀 https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md

**Comment by RLTek** [comment]
It is the ' in Tomorrow's. It thinks you have an open string, so you need to escape that character.
