### ISSUE TITLE
Css responds differently on mobile and desktop

### ISSUE THREAD

**Issue by GalKJ** [fac26/week-10-12-tfb-mark-gnnk#75]
The card animations on hover don't seem to be responsive in mobile view 📱 

![image](https://user-images.githubusercontent.com/99536044/228601205-e7a29093-7173-4a38-82a2-c6a28e9ecf2a.png)

Looks really great though ✨

**Comment by Psydwinder** [comment]
Heya @GalKJ,

Not quite sure what you mean by this. 

**_The card animations on hover don't seem to be responsive in mobile view 📱_**

Because hover effects don't exist on mobile phones either way, since there is no mouse cursor there to hover over buttons.
