### ISSUE TITLE
Refactor options

### ISSUE THREAD

**Issue by tonylomax** [fac26/week-10-12-tfb-mark-gnnk#84]
Instead of 
```
const isValidDate = isValid(date)
	if (!isValidDate) {
		return <span>Date not valid!</span>
	}
```

what about 

```
	if (!isValid(date)) {
		return <span>Date not valid!</span>
	}
```

or even better

```

return !isValid(date) ?  <span>Date not valid!</span> : null
	
```

There's a few other opportunities for some refactoring as you go 👀 

https://github.com/fac26/week-10-12-tfb-mark-gnnk/blob/18713335ad37bbe68c0665426995a8fc5a9997fb/src/components/layout/Days.js#L20-L23

**Comment by rockyrelay** [comment]
Thanks, Tony!

Took your suggestion and refactored into one return:

```javascript
	return !isValid(date) ? (
		<span>Date not valid!</span>
	) :	( <span>
			<time dateTime={date.toISOString()}>{format(date, 'EEEE do MMMM')}</time>
		</span>
	)
```
